### ISSUE TITLE
InsightFace support

### ISSUE THREAD

**Issue by IcelandicCenterArtificialIntelligence** [ashleykleynhans/comfyui-docker#1]
Should this docker support InsightFace?

**Comment by ashleykleynhans** [comment]
It supports whatever custom nodes you install.

**Comment by IcelandicCenterArtificialIntelligence** [comment]
That was fast! I mean, can it be installed after running it on RunPod?  If I'm right last time I tried it didn't work, or more exactly it did, but we would need to reinstall some stuff every time we launch the pod. But I'm trying again right now.

**Comment by ashleykleynhans** [comment]
Start the UI, install custom nodes.

**Comment by IcelandicCenterArtificialIntelligence** [comment]
It works fine now. Thanks.

**Comment by IcelandicCenterArtificialIntelligence** [comment]
Actually, it failed again after we terminated the pod and created a new one today.
The issues seems to be that insightface module is not installed. We can manually install it by connecting to the web terminal and "pip install insightface'. Then restart and it works. But the active venv seems to live, we assume, out of the workspace directory so it's flushed with every new pod restart.
Any ideas? For now we can manually install and restart, but it's not ideal.
If you want to replicate, you can use the comfyui manager to install [ComfyUI-LivePortraitKJ](https://github.com/kijai/ComfyUI-LivePortraitKJ).

And here is the log with the import errors before installing insightface.
`root@6202e3f1b02b:/# tail -f /workspace/logs/comfyui.log
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: /workspace/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json [DONE]
FETCH DATA from: /workspace/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/1742899825_extension-node-map.json [DONE]
FETCH DATA from: /workspace/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/1514988643_custom-node-list.json [DONE]
FETCH DATA from: /workspace/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/746607195_github-stats.json [DONE]
FETCH DATA from: /workspace/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/1742899825_extension-node-map.json [DONE]

Restarting... [Legacy Mode]

[START] Security scan
[DONE] Security scan

ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-07-21 12:39:22.506988
** Platform: Linux
** Python version: 3.11.9 (main, Apr 6 2024, 17:59:24) [GCC 11.4.0]
** Python executable: /workspace/ComfyUI/venv/bin/python3
** ComfyUI Path: /workspace/ComfyUI
** Log path: /workspace/ComfyUI/comfyui.log

Prestartup times for custom nodes:
5.0 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 24210 MB, total RAM 257776 MB
pytorch version: 2.3.1+cu121
xformers version: 0.0.27
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using xformers cross attention
[Prompt Server] web root: /workspace/ComfyUI/web
Traceback (most recent call last):
File "/workspace/ComfyUI/nodes.py", line 1931, in load_custom_node
module_spec.loader.exec_module(module)
File "", line 940, in exec_module
File "", line 241, in _call_with_frames_removed
File "/workspace/ComfyUI/custom_nodes/virtuoso-nodes/init.py", line 2, in
from .selectivecolor import SelectiveColor
File "/workspace/ComfyUI/custom_nodes/virtuoso-nodes/selectivecolor.py", line 10, in
import imageio
ModuleNotFoundError: No module named 'imageio'

Cannot import /workspace/ComfyUI/custom_nodes/virtuoso-nodes module for custom nodes: No module named 'imageio'
[Crystools INFO] Crystools version: 1.14.0
[Crystools INFO] CPU: AMD EPYC 7282 16-Core Processor - Arch: x86_64 - OS: Linux 6.5.0-41-generic
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 4090
[Crystools INFO] NVIDIA Driver: 550.90.07
Total VRAM 24210 MB, total RAM 257776 MB
pytorch version: 2.3.1+cu121
xformers version: 0.0.27
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Comfyroll Studio v1.76 : 175 Nodes Loaded
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
Workspace manager - Openning file hash dict
🦄🦄Loading: Workspace Manager (V2.1.0)
Traceback (most recent call last):
File "/workspace/ComfyUI/nodes.py", line 1931, in load_custom_node
module_spec.loader.exec_module(module)
File "", line 940, in exec_module
File "", line 241, in _call_with_frames_removed
File "/workspace/ComfyUI/custom_nodes/ComfyUI-LivePortraitKJ/init.py", line 1, in
from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
File "/workspace/ComfyUI/custom_nodes/ComfyUI-LivePortraitKJ/nodes.py", line 11, in
from .liveportrait.utils.cropper import Cropper
File "/workspace/ComfyUI/custom_nodes/ComfyUI-LivePortraitKJ/liveportrait/utils/cropper.py", line 10, in
from .face_analysis_diy import FaceAnalysisDIY
File "/workspace/ComfyUI/custom_nodes/ComfyUI-LivePortraitKJ/liveportrait/utils/face_analysis_diy.py", line 9, in
from insightface.app import FaceAnalysis
ModuleNotFoundError: No module named 'insightface'

Cannot import /workspace/ComfyUI/custom_nodes/ComfyUI-LivePortraitKJ module for custom nodes: No module named 'insightface'

Loading: ComfyUI-Manager (V2.46.3)
ComfyUI Revision: 2383 [11b74147] | Released on '2024-07-19'
Import times for custom nodes:
0.0 seconds: /workspace/ComfyUI/custom_nodes/websocket_image_save.py
0.0 seconds: /workspace/ComfyUI/custom_nodes/canvas_tab
0.0 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-mxToolkit
0.0 seconds (IMPORT FAILED): /workspace/ComfyUI/custom_nodes/virtuoso-nodes
0.0 seconds: /workspace/ComfyUI/custom_nodes/comfyui-workspace-manager
0.1 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI_MX_post_processing-nodes
0.1 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
0.2 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-Manager
0.2 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
0.2 seconds (IMPORT FAILED): /workspace/ComfyUI/custom_nodes/ComfyUI-LivePortraitKJ
0.7 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-KJNodes
2.9 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-Crystools

Starting server

To see the GUI go to: http://0.0.0.0:3001/
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: /workspace/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json [DONE]`

**Comment by ashleykleynhans** [comment]
The venv lives in /workspace and should be honored by ComfyUI because its activated when the worker starts:
https://github.com/ashleykleynhans/runpod-worker-comfyui/blob/main/start.sh#L10

Nothing I can do about this, this is just a serverless wrapper for ComfyUI, if ComfyUI has issues, log issues there, not here, I am not the developer of ComfyUI and there is nothing I can do.
